// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGx_W2tsOzKPFUyAjPSeJBuxPg9qEPtZI',
    appId: '1:206364635759:web:de286078342f4b9d07d39a',
    messagingSenderId: '206364635759',
    projectId: 'barbershop-dce73',
    authDomain: 'barbershop-dce73.firebaseapp.com',
    storageBucket: 'barbershop-dce73.appspot.com',
    measurementId: 'G-FJFE6P491B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDqy2nDSxztYOUWFz_4rFctLDJKWwo8UM',
    appId: '1:206364635759:android:0e0aeb4622ddb8fc07d39a',
    messagingSenderId: '206364635759',
    projectId: 'barbershop-dce73',
    storageBucket: 'barbershop-dce73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuiQowmLnpcbb7Ty0v13X_slEoS95XbkM',
    appId: '1:206364635759:ios:b95f762a3260d32507d39a',
    messagingSenderId: '206364635759',
    projectId: 'barbershop-dce73',
    storageBucket: 'barbershop-dce73.appspot.com',
    iosClientId: '206364635759-q9aolk3a2qbahatg6n9vi6nj5ilen035.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabalhoFlutter',
  );
}
